[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins", "alloc"]

[run]
target = "x86_64-toyos.json"

[build]
target = "x86_64-toyos.json"


[target.'cfg(target_os = "none")']
runner = "bootimage runner"
